<a href="https://colab.research.google.com/github/subhomoy-roy-choudhury/python-projects/blob/master/ANN_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [22]:
 tf.__version__

'2.2.0'

In [23]:
from google.colab import files
uploaded=files.upload()

Saving datasets_180_408_data.csv to datasets_180_408_data (1).csv


In [24]:
dataset = pd.read_csv('datasets_180_408_data.csv') 
x = dataset.iloc[:,2:] 
y = dataset.iloc[:, 1].values
x

radius_mean  texture_mean  ...  fractal_dimension_worst  Unnamed: 32
0          17.99         10.38  ...                  0.11890          NaN
1          20.57         17.77  ...                  0.08902          NaN
2          19.69         21.25  ...                  0.08758          NaN
3          11.42         20.38  ...                  0.17300          NaN
4          20.29         14.34  ...                  0.07678          NaN
..           ...           ...  ...                      ...          ...
564        21.56         22.39  ...                  0.07115          NaN
565        20.13         28.25  ...                  0.06637          NaN
566        16.60         28.08  ...                  0.07820          NaN
567        20.60         29.33  ...                  0.12400          NaN
568         7.76         24.54  ...                  0.07039          NaN

[569 rows x 31 columns]

In [25]:
y

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'B', 'M',
       'B', 'M', 'M', 'B', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

# New Section

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:765: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:706: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)


In [29]:
x_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.01614761,
        -0.38503402,         nan],
       [-0.93798972,  0.68051405, -0.94820146, ...,  0.09669004,
        -0.38615797,         nan],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.20050207,
        -0.75144254,         nan],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.71542314,
        -0.11978123,         nan],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.58157125,
        -1.00601779,         nan],
       [-0.73694129,  1.14989702, -0.71226578, ..., -1.25895095,
         0.21515662,         nan]])

In [30]:
ann = tf.keras.models.Sequential()

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [33]:
ann.add(tf.keras.layers.Dense(units=1))

In [34]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [35]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
15/15 [==============================] - 0s 3ms/step - loss: 0.3581
Epoch 2/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3480
Epoch 3/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3386
Epoch 4/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3298
Epoch 5/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3214
Epoch 6/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3135
Epoch 7/100
15/15 [==============================] - 0s 2ms/step - loss: 0.3062
Epoch 8/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2992
Epoch 9/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2931
Epoch 10/100
15/15 [==============================] - 0s 3ms/step - loss: 0.2874
Epoch 11/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2820
Epoch 12/100
15/15 [==============================] - 0s 2ms/step - loss: 0.2773
Epoch 13/100
15/15 [=================

In [41]:
ann.fit(x_test, y_test, batch_size = 32, epochs = 100)

Epoch 1/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2443
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2443
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2442
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2441
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2440
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2439
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2438
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2438
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2436
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2436
Epoch 11/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2435
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2434
Epoch 13/100
4/4 [==============================] - 0s 4ms/st

In [42]:
y_pred=ann.predict(x_test)
y_pred=(y_test>0.5)

In [43]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[67  0]
 [ 0 47]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        67
           1       1.00      1.00      1.00        47

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

